version: 2.1
orbs:
  puppeteer: threetreeslight/puppeteer@0.1.2
jobs:
  end-to-end-test:
    executor:
      name: puppeteer/default
    steps:
      - checkout
      - run:
          name: Run test
          command: |
            npm install
            npm run test
workflows:
    end-to-end-test:
      jobs:
        - end-to-end-test